name: Tutora
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+10

environment:
  sdk: ">=2.16.2 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_core: ^1.20.0
  firebase_auth: ^3.6.2
  firebase_storage: ^10.3.11
  table_calendar: ^3.0.6
  get: ^4.6.5
  animated_splash_screen: ^1.3.0
  http: ^0.13.5
  google_fonts: ^3.0.1
  syncfusion_flutter_pdfviewer: ^19.2.47-beta  
  path_provider: ^2.0.11
  cloud_firestore: ^3.4.6
  smooth_page_indicator: ^1.0.0+2
  firebase_messaging: ^13.0.1
  awesome_notifications: ^0.6.21
  flutter_local_notifications: ^11.0.0
  image_picker: ^0.8.5+3
  path: ^1.8.1
  shared_preferences: ^2.0.15
  flutter_downloader: ^1.8.4
  dio: ^4.0.6
  permission_handler: ^10.2.0
  external_path: ^1.0.3
  custom_rating_bar: ^2.0.4
  dropdown_button2: ^1.9.1
  animated_text_kit: ^4.2.2
  font_awesome_flutter: ^10.3.0
  change_app_package_name: ^1.1.0
  flutter_phone_direct_caller: ^2.1.1


  
 

dev_dependencies:
  flutter_test:
    sdk: flutter
#   flutter_launcher_icons: ^0.11.0

# flutter icons:
#   android: "launcher_icon"
#   ios: true
#   image_path: "assets/images/tutora.png"
#   adaptive_icon_background: "#191919" 

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/rewords.png
    - assets/images/handshake.gif
    - assets/images/mike.gif
    - assets/images/teacher.gif
    - assets/images/scholarships.png
    - assets/images/notes.png
    - assets/images/schedule.png
    - assets/images/settings.png
    - assets/images/studentnearme.png
    - assets/images/verify.png
    - assets/images/rewords.png
    - assets/images/coachings.png
    - assets/images/schedule.png
    - assets/images/comingsoon.gif
    - assets/images/comingsoon.png
    - assets/images/tutora.png
    - assets/images/extraearning.png
    - assets/images/stepstofollow.png
    - assets/inimages/6.png
    - assets/inimages/4.png
    - assets/inimages/7.png
    - assets/inimages/1.png
    - assets/inimages/2.png
    - assets/inimages/3.png
    - assets/inimages/5.png
    - assets/inimages/8.png
    - assets/inimages/l1.png
    - assets/inimages/dp.png
    - assets/inimages/LOGO.png
    - assets/inimages/logob.png
    - assets/images/tutors.png
    - assets/images/notes.png
    - assets/images/proto.jpg
    - assets/images/rana.jpg
    - assets/images/aboutus.png
    - assets/images/247.png
    - assets/images/ci.png
    - assets/images/sayed.jpg
    - assets/images/lian.jpg
    - assets/images/akash1.jpg
    - assets/images/connectionstate.gif
    - assets/images/shahab.jpg
    - assets/images/ictCourse.png
    - assets/images/lader.gif
    - assets/images/mentors.png
    - assets/images/dailytask.png
    - assets/images/congi.gif
    - assets/images/profile.png
    - assets/images/tutorsdp.png
    - assets/images/courses.png
    - assets/images/coaching.png
    - assets/images/about.png
    - assets/images/review.png
    - assets/images/qualityeducation.gif
    - assets/images/vgif.gif
    - assets/images/studentnearme.png
    - assets/images/tutionChai.png
    - assets/images/britti.png
    - assets/images/note.png
    - assets/images/tutionSomuh.png
    - assets/images/juggotaJachai.png
    - assets/images/timetable.png
    - assets/images/kajerpoddhoti.png
    - assets/images/tutor.png
    - assets/images/britti.png
    - assets/images/quiz.png
    - assets/images/about.png
    - assets/images/jiggasa.png
    - assets/images/reward.png
    - assets/images/coaching.png
    - assets/images/coming.png
    - assets/images/jogajug.png



   
   
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
fonts:
    - family: Hind Siliguri Regular
      fonts:
        - asset: fonts/HindSiliguri-Regular.ttf
   
    - family: Hind Siliguri Regular
      fonts:
        - asset: fonts/HindSiliguri-Medium.ttf
    - family: Hind Siliguri Regular
      fonts:
         - asset: fonts/HindSiliguri-Light.ttf
    - family: Hind Siliguri Regular
      fonts:
        - asset: fonts/HindSiliguri-Bold.ttf
    - family: Sabrena Tonny Mj
      fonts:
        - asset: fonts/SabrenaTonnyMJ.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
